package com.array;
/* WHAT IS ARRAY?
  ARRAY IS AN OBJECT
  ARRAY IS COLLECTION OF homogeneous (or)SIMULAR DATA TYPE
  it is A LINEAR collection of DATA STRUCTURE
  ON INBUILD CLASS
  IT IS INDEPENDENT OBJECT
  

WHY WE NEED ARRAY?
		TO STORE ANY VALUE WE WILL USE DATA STRUCTURE AND WE HAVING MANY DIFFERENT  TYPE OF DATA STRUCTURE
		PRIMITATIVE DATA STRUCTURE 
         PRIMIRIVE ONLY STORE AT A TIME 
      EX: I HAVE TO STORE AGE OF A PERSON WE HAVE TO CREATE THE INT VARIABLE TO STORE THE VALUE IF YOU WANT TO STORE GROUP OF DATA NO .OF VARAIABLE
         STORE 5 STUID 
         int id1=101;
         int id2=102;
         int id3=103;
         int id4=104;
         int id5=105;
         the number of variables of more and we have to remember all the variables to perform (curd operation)
         the no of lines of more
         the data is stored in non-linear order and the data is not stored in group all the varaiable are indudual
		NON PRIMITIVE DATA STRUCTURE


 TO CREATE AN ARRAY OBJECT
 STEP 1:
	 SYNTAX: DATA TYPE[] VARIABLE NAME 
	 EX:INT[]ID
 [] REPRESENT ARRAY AND ALSO TELL ABOUT DEMISION OF GIVEN ARRAY
 
   STEP 2:
	   OBJECT CREATION
	   SYTAX: VARIABLE NAME NEW KEYWORD DATATYPE SIZE
	   EX: ID=NEW INT[5];
		INT [] ID=NEW ID[5];

INTILAZATION:
	ID[0]=101;
	ID[1]=102;
	ID[2]=103;
	ID[3]=104;
	ID[4]=105;

/*LEGTH VARAIALE :
	IT IS A VARIALE WHICH WILL RETURN NO.OF . BUCKETS IN AN ARRAY
ARRAY NAME.LENGTH

INDEX:
	IT IS A POSITIVE INTEGER NO IT WILL START FROM 0.
	-1 IS INVALID 
	ITS IS ALWAYS RANGING FROM 0 TO LENGTH-1
	EX: SIZE OF ARRAY IS 10
	INDEX IS RANGING FROM O T0 9
	0 INNDEX IS CALLED AS LOWER BOND OF GIVEN ARRAY
	LAST INDEX IS UPPER BOND LEGTH-1 THEN MIDDLE INDEX IS MIDDLE BOND LEGTH-1/2;

DECLARATO CREACTION AND INTIALIZATION
 * 	ARRAY LITERIALS 
 *  DATATYPE [] VARIALEAME = {VALUE 1,VALUE2, VALUE 3,VALUE 4,VALUE4}
 
 */
	

public class Sample 
 {

}
